config/routes.rb
Rails.application.routes.draw do
  get "cities/index"
  get "cities/show"
  get "pages/about"
  get "countries/index"
  get "countries/show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get 'about', to: 'pages#about'
  resources :countries, only: [:index, :show]
  resources :cities, only: [:index, :show]
  resources :weather_reports, only: [:index, :show]

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
  has_many :weather_reports
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
  has_many :weather_reports, through: :cities
end

app/models/weather_report.rb
class WeatherReport < ApplicationRecord
  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @countries = Country.all
    @cities = City.all
    if params[:query].present?
      @cities = @cities.where("name LIKE ?", "%#{params[:query]}%")
    end
    if params[:country_id].present?
      @cities = @cities.where(country_id: params[:country_id])
    end

    @cities = @cities.page(params[:page]).per(10)
  end
  end

  def show
    @city = City.includes(:weather_reports).find(params[:id])
    @weather_reports = @city.weather_reports.page(params[:page]).per(5) 
  end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = if params[:query].present?
      Country.where("name LIKE ?", "%#{params[:query]}%")
    else
      Country.all
    end
    @countries = @countries.page(params[:page]).per(5)
  end

  def show
    @country = Country.includes(:cities).find(params[:id])

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  def home
  end
end

app/controllers/weather_reports_controller.rb
class WeatherReportsController < ApplicationController
  def index
    @weather_reports = WeatherReport.all

    if params[:query].present?
      @weather_reports = @weather_reports.where("description LIKE ?", "%#{params[:query]}%")
    end
    if params[:start_date].present? && params[:end_date].present?
      @weather_reports = @weather_reports.where(date: params[:start_date]..params[:end_date])
    end
  @weather_reports = @weather_reports.page(params[:page]).per(10)
  end
end
def show
  @weather_report = WeatherReport.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/weather_reports_helper.rb
module WeatherReportsHelper
end

app/views/cities/_city.html.erb
<div class="city-item">
  <h2><%= link_to city.name, city_path(city) %></h2>
  <p>Population: <%= city.population %></p>
  <p>Country: <%= city.country.name %></p>
</div>

app/views/cities/index.html.erb
<h1>Cities</h1>

<%= link_to 'Home', root_path, class: 'btn btn-info' %>
<%= link_to 'About Us', about_path, class: 'btn btn-info' %>
  <%= link_to 'Browse Countries', countries_path, class: 'btn btn-primary' %>
  <%= link_to 'Explore Cities', cities_path, class: 'btn btn-primary' %>
   <%= link_to 'Weather Report', weather_reports_path, class: 'btn btn-primary' %>

<h1>Cities</h1>

<%= form_with url: cities_path, method: :get, local: true do |form| %>
  <%= form.label :query, "Search Cities by Name" %>
  <%= form.text_field :query, value: params[:query] %>

  <%= form.label :country_id, "Filter by Country" %>
  <%= form.collection_select :country_id, @countries, :id, :name, prompt: "Select a Country", selected: params[:country_id] %>

  <%= form.submit "Search" %>
<% end %>

<%= render partial: 'city', collection: @cities %>

<%= paginate @cities %>

app/views/cities/show.html.erb
<h1><%= @city.name %></h1>
<p>Population: <%= @city.population %></p>
<p>Country: <%= @city.country.name %></p>

<h2>Weather Reports</h2>
<ul>
  <% @weather_reports.each do |report| %>
    <li>
      Date: <%= report.date %>, Temperature: <%= report.temperature %>°C, Description: <%= report.description %>
    </li>
  <% end %>
</ul>

app/views/countries/_country.html.erb
<div class="country">
  <h3><%= country.name %></h3>
  <p>Population: <%= number_with_delimiter(country.population) %></p>
  <p>Continent: <%= country.continent %></p>
  <%= link_to "View Details", country_path(country), class: "btn btn-primary" %>
</div>

app/views/countries/index.html.erb
<h1>Countries</h1>
<%= link_to 'Home', root_path, class: 'btn btn-info' %>
<%= link_to 'About Us', about_path, class: 'btn btn-info' %>
  <%= link_to 'Browse Countries', countries_path, class: 'btn btn-primary' %>
  <%= link_to 'Explore Cities', cities_path, class: 'btn btn-primary' %>
   <%= link_to 'Weather Report', weather_reports_path, class: 'btn btn-primary' %>
   <h1>All Countries</h1>
<ul>
  <% @countries.each do |country| %>
    <li><%= link_to country.name, country_path(country) %></li>
  <% end %>
</ul>
<ul>
  <% @countries.each do |country| %>
    <li>
      <%= link_to country.name, country_path(country) %> - Population: <%= country.population %>
    </li>
  <% end %>
</ul>
  <%= paginate @countries %>
<h1>Countries</h1>
<%= form_with(url: countries_path, method: :get, local: true) do |form| %>
  <%= form.label :query, "Search Countries" %>
  <%= form.text_field :query, value: params[:query] %>
  <%= form.submit "Search" %>
<% end %>
<%= render @countries %>
<%= paginate @countries %>

app/views/countries/show.html.erb
<h1><%= @country.name %></h1>
<p>Population: <%= @country.population %></p>
<p>Continent: <%= @country.continent %></p>

<h2>Cities in <%= @country.name %></h2>
<ul>
  <% @cities.each do |city| %>
    <li>
      <%= link_to city.name, city_path(city) %> - Population: <%= city.population %>
    </li>
  <% end %>
</ul>
<h1><%= @city.name %></h1>
<p>Population: <%= @city.population %></p>
<p>Country: <%= link_to @city.country.name, country_path(@city.country) %></p>

<h2>Weather Reports</h2>
<ul>
  <% @city.weather_reports.each do |report| %>
    <li><%= link_to report.date, weather_report_path(report) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Intro" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MgWV5lW9B46bgM18+r18TDyihS1xtY7zp1ahmFuJL95APmZZHXbRXRaFwK8K4Lox" crossorigin="anonymous">

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  </head>

  <body>
    <%= yield %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">My App</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Countries", countries_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Cities", cities_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
      <li><%= link_to 'Weather Reports', weather_reports_path, class: "nav-link" %></li>

    </ul>
  </div>
</nav>
  </body>
</html>

app/views/pages/about.html.erb
<%= link_to 'Home', root_path, class: 'btn btn-info' %>
<%= link_to 'About Us', about_path, class: 'btn btn-info' %>
  <%= link_to 'Browse Countries', countries_path, class: 'btn btn-primary' %>
  <%= link_to 'Explore Cities', cities_path, class: 'btn btn-primary' %>
   <%= link_to 'Weather Report', weather_reports_path, class: 'btn btn-primary' %>
<div class="container">
  <h1>About Our Data Sources</h1>
  <p>This application gathers data from public sources to display information on countries and cities. More specifcally thier weather reports. This is a weather reporting page. Visit the homepage to start exploring.</p>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>Welcome to Our App</h1>
  <p>Explore data about countries and cities from around the world!</p>

  <%= link_to 'Home', root_path, class: 'btn btn-info' %>
<%= link_to 'About Us', about_path, class: 'btn btn-info' %>
  <%= link_to 'Browse Countries', countries_path, class: 'btn btn-primary' %>
  <%= link_to 'Explore Cities', cities_path, class: 'btn btn-primary' %>
   <%= link_to 'Weather Report', weather_reports_path, class: 'btn btn-primary' %>
</div>

app/views/weather_reports/_weather_report.html.erb
<div class="weather-report-item">
  <h2>Weather Report on <%= weather_report.date %></h2>
  <p>Temperature: <%= weather_report.temperature %> °C</p>
  <p>Description: <%= weather_report.description %></p>
  <p>City: <%= weather_report.city.name %></p>
</div>

app/views/weather_reports/index.html.erb
<h1>Weather Reports</h1>
<%= link_to 'Home', root_path, class: 'btn btn-info' %>
<%= link_to 'About Us', about_path, class: 'btn btn-info' %>
  <%= link_to 'Browse Countries', countries_path, class: 'btn btn-primary' %>
  <%= link_to 'Explore Cities', cities_path, class: 'btn btn-primary' %>
   <%= link_to 'Weather Report', weather_reports_path, class: 'btn btn-primary' %>
<ul>
  <% @weather_reports.each do |report| %>
    <li>
      <%= report.city.name %> - <%= report.date %>: <%= report.temperature %>°C, <%= report.description %>
    </li>
  <% end %>
</ul>
<h1>Weather Reports</h1>

<%= form_with url: weather_reports_path, method: :get, local: true do |form| %>
  <%= form.label :query, "Search by Description" %>
  <%= form.text_field :query, value: params[:query] %>

  <%= form.label :start_date, "Start Date" %>
  <%= form.date_field :start_date, value: params[:start_date] %>

  <%= form.label :end_date, "End Date" %>
  <%= form.date_field :end_date, value: params[:end_date] %>

  <%= form.submit "Search" %>
<% end %>

<%= render partial: 'weather_report', collection: @weather_reports %>

<%= paginate @weather_reports %>

app/views/weather_reports/shows.html.erb
<h1>Weather Report for <%= @weather_report.city.name %></h1>
<p>Date: <%= @weather_report.date %></p>
<p>Temperature: <%= @weather_report.temperature %>°C</p>
<p>Description: <%= @weather_report.description %></p>